Reduce h2 load even further since it crashes when getting to much traffic
If relevant, h2 throws a KeyError escalated from
h2.exceptions.ProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED